### PR TITLE
Added vertex/module-tax-staging

### PR DESCRIPTION
**Pull request by slackerzz**
Upgrading a project to Magento 2.4.2 I discovered another vertex module bundled `vertex/module-tax-staging`

### CODE REVIEW

**Comment by jissereitsma** [comment]
Thanks. I'm going to close this PR, because it was made to the Magento 2.4.0 branch and in that branch the package doesn't exist. I will make the change to the 2.4.2 branch instead.

**Comment by jissereitsma** [comment]
Actually, this already exists: https://github.com/yireo/magento2-replace-bundled/blob/magento-2.4.2/composer.json#L39

Which package did you install? Perhaps you are using a specific branch?

**Comment by slackerzz** [comment]
Nevermind, I was on the wrong branch (2.4.0)

**Comment by jissereitsma** [comment]
No worries :)

**Pull request closed without merging**
